### ISSUE TITLE
US23 As an author, I want to be able to use my web-browser to manage my profile

### ISSUE THREAD

**Issue by bkhunter** [pmaidens/CMPUT404-project#23]

**Comment by pmaidens** [comment]
@kchow3 when the backend author api is done, we can probably remove the backend tag.

**Comment by pmaidens** [comment]
PUT to authors/{id} returns a 403 even if authorized.

**Comment by pmaidens** [comment]
Works now.

**Comment by sjpartri** [comment]
We need to find a way so that when you accept a friend request, it will refresh the profile page and then add that to your friends table. It works when you refresh the page but doesn't do it instantly.
