### ISSUE TITLE
US26 As a server admin, I want to be able allow users to sign up but require my OK

### ISSUE THREAD

**Issue by bkhunter** [pmaidens/CMPUT404-project#26]
- Require the OK  to finally be on my server

**Comment by pmaidens** [comment]
Anyone know if django will do this for us?

**Comment by kchow3** [comment]
There is a django module that I am going to add in to do registrations for us. https://pypi.python.org/pypi/django-inspectional-registration

**Comment by kchow3** [comment]
Hitting the /rest-auth/registration will create a user that is not active and will not be able to get pass /rest-auth/login. To get a user active, login to the admin panel and you can filter by non active users and just edit the user to active status.
